project:
  type: website
  output-dir: docs

website:
  title: "2024년도 동계 WORKSHOP"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/guebin/PP2024WIN
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true    
    
    
